export const getPortmoneValue = ({
  description,
  emailAddress,
  shopOrderNumber,
  lang,
  payeeId,
  billAmount,
  billCurrency,
}) => ({
  paymentTypes: {
    card: "Y",
    portmone: "Y",
    token: "N",
    clicktopay: "Y",
    createtokenonly: "N",
  },
  priorityPaymentTypes: {
    card: "1",
    portmone: "2",
    token: "0",
    clicktopay: "1",
    createtokenonly: "0",
  },
  payee: {
    payeeId,
    login: "",
    dt: "",
    signature: "",
    shopSiteId: "",
  },
  order: {
    description,
    shopOrderNumber,
    billAmount,
    attribute1: "1",
    attribute2: "2",
    attribute3: "3",
    attribute4: "4",
    attribute5: "",
    successUrl: "",
    failureUrl: "",
    preauthFlag: "N",
    billCurrency,
    encoding: "",
  },
  token: {
    tokenFlag: "N",
    returnToken: "N",
    token: "",
    cardMask: "",
    otherPaymentMethods: "Y",
    sellerToken: "",
  },
  payer: {
    lang,
    emailAddress,
  },
  style: {
    type: "light",
    logo: "",
    logoWidth: "300px",
    backgroundColorHeader: "#ff0000",
    backgroundColorButtons: "#212121",
    colorTextAndIcons: "#212121",
    borderColorList: "#123456",
    bcMain: "#00000050",
  },
});
